<?php $bannerCollection = $this->getBanners(); ?>
<?php if ($bannerCollection->getSize() > 0): ?>
    <div class="owl-slider">
        <?php foreach ($bannerCollection as $item): ?>
            <div class="item">
                <?php if ($item->getSlideUrl()): ?>
                    <a href="<?php echo $item->getSlideUrl() ?>" class="main-link" target="<?php echo $item->getSlideTarget() ?>">
                <?php endif; ?>
                <img class="lazyOwl" data-src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $item->getFilename(); ?>"/>
                <?php if ($item->getSlideUrl()): ?>
                    </a>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
