<?php if (Mage::getStoreConfig('slideshow/general/enable')): ?>
    <?php
        $bannerCollection = $this->getBanners();
    ?>
    <?php if (count($bannerCollection) > 0): ?>
        <div id="main-slider">
            <?php foreach ($bannerCollection as $item): ?>
                <div class="item">
                    <?php if ($item->getSlideUrl()): ?>
                        <a href="<?php echo $item->getSlideUrl() ?>" class="main-link" target="<?php echo $item->getSlideTarget() ?>">
                    <?php endif; ?>
                    <img class="lazyOwl" data-src="<?php echo Mage::getUrl('media/') . $item->getFilename() ?>"/>
                    <?php if ($item->getSlideUrl()): ?>
                        </a>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div>
        <script type="text/javascript">
            jQuery(document).ready(function () {
                jQuery("#main-slider").owlCarousel({
                    autoPlay: true, // int / boolean, default: 5s
                    singleItem: true,
                    pagination: false,
                    lazyLoad: true,
                    lazyEffect: false,
                    navigation:true
                });
            });
        </script>
    <?php endif; ?>
<?php endif; ?>
