<?php $slides = $this->getSlides(); ?>
<?php if ($slides->getSize() > 0): ?>
    <div class="slick-slider"<?php if (Mage::helper('mp_slideshow')->isValidJson($this->getData('configuration'))): ?> data-slick='<?php echo $this->getData('configuration') ?>'<?php endif; ?>>
        <?php foreach ($slides as $item): ?>
            <div>
                <?php if ($item->getSlideUrl()): ?>
                    <a href="<?php echo $item->getSlideUrl() ?>" target="<?php echo $item->getSlideTarget() ?>">
                <?php endif; ?>
                <img data-lazy="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $item->getFilename(); ?>"/>
                <?php if ($item->getSlideUrl()): ?>
                    </a>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
